// only for admin
export const REQUEST_CREATE_PRODUCT = 'REQUEST_CREATE_PRODUCT'
export const SUCCESS_CREATE_PRODUCT = 'SUCCESS_CREATE_PRODUCT'
export const FAILED_CREATE_PRODUCT = 'FAILED_CREATE_PRODUCT'

// only for admin
export const REQUEST_UPDATE_PRODUCT = 'REQUEST_UPDATE_PRODUCT'
export const SUCCESS_UPDATE_PRODUCT = 'SUCCESS_UPDATE_PRODUCT'
export const FAILED_UPDATE_PRODUCT = 'FAILED_UPDATE_PRODUCT'

// only for admin
export const REQUEST_DELETE_PRODUCT = 'REQUEST_DELETE_PRODUCT'
export const SUCCESS_DELETE_PRODUCT = 'SUCCESS_DELETE_PRODUCT'
export const FAILED_DELETE_PRODUCT = 'FAILED_DELETE_PRODUCT'


export const REQUEST_GET_ALL_PRODUCTS = 'REQUEST_GET_ALL_PRODUCTS'
export const SUCCESS_GET_ALL_PRODUCTS = 'SUCCESS_GET_ALL_PRODUCTS'
export const FAILED_GET_ALL_PRODUCTS = 'FAILED_GET_ALL_PRODUCTS'


export const REQUEST_GET_SINGLE_PRODUCT = 'REQUEST_GET_SINGLE_PRODUCT'
export const SUCCESS_GET_SINGLE_PRODUCT = 'SUCCESS_GET_SINGLE_PRODUCT'
export const FAILED_GET_SINGLE_PRODUCT = 'FAILED_GET_SINGLE_PRODUCT'
export const CLEAR_ALL_ERROR = 'CLEAR_ALL_ERROR'
