
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAILED_LOGIN = 'FAILED_LOGIN'

export const REQUEST_REGISTER = 'REQUEST_REGISTER'
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const FAILED_REGISTER = 'FAILED_REGISTER'

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT'
export const FAILED_LOGOUT = 'FAILED_LOGOUT'
